version: '3'

services:
   db:
     image: mysql:5.7
     ports:
       - "3308:3306"      
     volumes:
       - /opt/mysqldk:/var/lib/mysql
       - /opt/docker/scripts:/scripts
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 9vu2GHi4Tf50FUo8
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8002:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - /opt/docker/scripts:/scripts
       - /opt/sites/wp/:/var/www/html/      
volumes:
    db_data:
